theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
safe: true
source: .
destination: ./_site
incremental: false

# Include copy code script
head_scripts:
  - /assets/scripts/copyCode.js